default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  password: postgres

development:
  <<: *default
  database: fyp_development

test:
  <<: *default
  database: fyp_test


production:
  <<: *default
  database: fyp_production
  password: <%= ENV['FYP_DATABASE_PASSWORD'] %>
